#!/bin/bash

# Test script to validate environment variable creation functionality
# This simulates the environment variable file creation from manage-infra.sh

set -e

echo "=== Testing Environment Variable Creation ==="

# Source test variables
source test_infra_vars.env

# Test the here-document functionality
GLOBAL_ENV_VARS_FILE="/tmp/test_env_vars_creation.$$"

echo "Creating test environment variables file: ${GLOBAL_ENV_VARS_FILE}"

# Simulate the environment variable file creation from manage-infra.sh
cat > "${GLOBAL_ENV_VARS_FILE}" <<'ENVEOF'
# Variables for infrastructure scripts - Sourced by sub-scripts
# Generated by test script
export ENVIRONMENT="${ENVIRONMENT}"
export DOMAIN_NAME="${DOMAIN_NAME}"
export DB_PASSWORD="${DB_PASSWORD}"
export POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
export API_SECRET_KEY="${API_SECRET_KEY}"
export API_MASTER_KEY="${API_MASTER_KEY}"
export API_VERSION="${API_VERSION}"
export ALGORITHM="${ALGORITHM:-HS256}"
export ACCESS_TOKEN_EXPIRE_MINUTES="${ACCESS_TOKEN_EXPIRE_MINUTES:-30}"
export REDIS_URL="${REDIS_URL:-redis://redis:6379/1}"
export LOG_DIRECTORY="${LOG_DIRECTORY:-/app/logs}"
export SYNC_DATABASE_URL="postgresql+asyncpg://barcodeboachiefamily:${DB_PASSWORD}@db/barcode_api"
export DATABASE_URL="postgresql+asyncpg://barcodeboachiefamily:${DB_PASSWORD}@db/barcode_api"
ENVEOF

echo "Environment variables file created successfully:"
echo "--- File contents ---"
cat "${GLOBAL_ENV_VARS_FILE}"
echo "--- End of file ---"

# Test sourcing the file
echo "Testing sourcing of the environment variables file..."
source "${GLOBAL_ENV_VARS_FILE}"

echo "Variables after sourcing:"
echo "ENVIRONMENT: $ENVIRONMENT"
echo "DOMAIN_NAME: $DOMAIN_NAME"
echo "REDIS_URL: $REDIS_URL"
echo "DATABASE_URL: $DATABASE_URL"

# Clean up
rm -f "${GLOBAL_ENV_VARS_FILE}"
echo "Test completed successfully!"
