"""add_last_request_to_users

Revision ID: f84c9d84f67b
Revises: 5c84ccd920ba
Create Date: 2024-11-23 03:31:21.370643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f84c9d84f67b'
down_revision: Union[str, None] = '5c84ccd920ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_request', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_request')
    # ### end Alembic commands ###
