version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_ENV=${ENVIRONMENT} # production, development
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./app:/app/app:ro
      - ./alembic:/app/alembic:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2G

  redis:
    image: redislabs/rejson:latest
    ports:
      - "6379:6379"
    volumes:
      - /opt/thebarcodeapi/${ENVIRONMENT}/releases/data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    command: ["redis-server", "--appendonly", "yes"]

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - /opt/thebarcodeapi/${ENVIRONMENT}/releases/data/postgres:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - BARCODE_DB_USER=barcodeboachiefamily
      - BARCODE_DB_PASSWORD=${DB_PASSWORD}
      - BARCODE_DB_NAME=barcode_api
      - POSTGRES_HOST_AUTH_METHOD=md5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U barcodeboachiefamily -d barcode_api"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1G

networks:
  default:
    name: barcodeapi_network
