#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $BARCODE_DB_USER WITH PASSWORD '$BARCODE_DB_PASSWORD';
    CREATE DATABASE $BARCODE_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $BARCODE_DB_NAME TO $BARCODE_DB_USER;
    \c $BARCODE_DB_NAME
    GRANT ALL ON SCHEMA public TO $BARCODE_DB_USER;
EOSQL