# .github/workflows/ci-cd.yml

name: CI/CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: |
        echo 'Installing dependencies'
        npm ci

    - name: Run linter
      run: |
        echo 'Running linter'
        npm run lint

    # Uncomment this step when you're ready to run tests
    # - name: Run tests
    #   run: npm test

    - name: Build
      run: |
        echo 'Building the app'
        npm run build

    - name: Deploy
      run: |
        echo 'Deploying the app'
        sudo mkdir -p /opt/thebarcodeapi/releases
        NEW_RELEASE="/opt/thebarcodeapi/releases/release-$(date +%Y%m%d%H%M%S)"
        sudo mkdir -p "$NEW_RELEASE"
        sudo cp -R "$(pwd)/build/." "$NEW_RELEASE/"
        sudo ln -sfn "$NEW_RELEASE" /opt/thebarcodeapi/current
        cd /opt/thebarcodeapi/releases && ls -1dt */ | tail -n +6 | xargs sudo rm -rf
        sudo systemctl reload nginx
        sudo chown -R www-data:www-data /opt/thebarcodeapi