name: theBarcodeApi Infrastructure Setup

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
  ENVIRONMENT: ${{ secrets.ENVIRONMENT }}

jobs:
  setup-infrastructure:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Update system
      run: |
        echo "Updating system packages..."
        sudo apt-get update
        sudo apt-get upgrade -y
      continue-on-error: true

    - name: Install Nginx
      run: |
        echo "Installing Nginx..."
        sudo apt-get install -y nginx

    - name: Create Nginx configuration script
      run: |
        echo "Creating Nginx configuration script..."
        cat << 'EOF' > nginx_config.sh
        #!/bin/bash
        set -e

        # Read environment variables from file
        source /tmp/nginx_env_vars

        echo "Configuring Nginx for $DOMAIN_NAME in $ENVIRONMENT environment..."

        # Create Nginx configuration
        cat > /etc/nginx/sites-available/thebarcodeapi << EOL
        server {
            listen 80;
            server_name $DOMAIN_NAME;
            root /opt/thebarcodeapi/$ENVIRONMENT/current;
            index index.html;
            location / {
                try_files \$uri \$uri/ =404;
            }
        }
        EOL

        echo "Created Nginx configuration file."

        # Create symlink to sites-enabled
        ln -sf /etc/nginx/sites-available/thebarcodeapi /etc/nginx/sites-enabled/
        echo "Created symlink in sites-enabled."

        # Test Nginx configuration
        nginx -t
        echo "Nginx configuration test passed."

        # Reload Nginx
        systemctl reload nginx
        echo "Nginx reloaded successfully."

        echo "Nginx configuration completed."

        # Clean up
        rm /tmp/nginx_env_vars
        EOF
        chmod +x nginx_config.sh

    - name: Configure Nginx
      run: |
        echo "Preparing to run Nginx configuration script..."
        # Create a temporary file with environment variables
        echo "DOMAIN_NAME=${{ env.DOMAIN_NAME }}" > /tmp/nginx_env_vars
        echo "ENVIRONMENT=${{ env.ENVIRONMENT }}" >> /tmp/nginx_env_vars

        echo "Running Nginx configuration script..."
        sudo ./nginx_config.sh

        # Clean up (in case the script didn't run to completion)
        rm -f /tmp/nginx_env_vars

    - name: Install Node.js
      run: |
        echo "Installing Node.js 20.x..."
        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        sudo apt-get install -y nodejs

    - name: Verify Installation
      run: |
        echo "Verifying installations..."
        echo "Nginx version:"
        nginx -v
        echo "Node.js version:"
        node -v
        echo "npm version:"
        npm -v

    - name: Check Nginx Configuration
      run: |
        echo "Checking Nginx configuration..."
        sudo nginx -t
        echo "Checking Nginx status..."
        sudo systemctl status nginx

    - name: Print Environment Info
      run: |
        echo "Deployed to ${{ env.ENVIRONMENT }} environment"
        echo "Domain: ${{ env.DOMAIN_NAME }}"