name: theBarcodeApi Infrastructure Setup

on:
  workflow_dispatch:

env:
  # Domain name for the application, used by Nginx and other services.
  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
  # Deployment environment (e.g., staging, production). Used for path creation and configuration templating.
  ENVIRONMENT: ${{ vars.ENVIRONMENT }}
  # Sudo password for privileged operations on the self-hosted runner.
  SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
  # Database password for the main application user.
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  # PostgreSQL superuser (postgres user) password.
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  # Secret key for API authentication (e.g., JWT signing).
  API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
  # Master API key for administrative API access.
  API_MASTER_KEY: ${{ secrets.API_MASTER_KEY }}
  # Version of the API, used in .env files and potentially for tagging.
  API_VERSION: ${{ vars.API_VERSION }}

jobs:
  infra-ci-job:
    name: Setup Server Infrastructure
    runs-on: self-hosted

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3

    - name: Run Infrastructure and Initial Deployment Script
      run: |
        bash scripts/infra/manage-infra.sh

    # Prints final environment information for debugging and record-keeping.
    - name: Print final environment information
      run: |
        echo "Infrastructure setup workflow completed for environment: ${{ env.ENVIRONMENT }}"
        echo "Domain configured (if applicable): ${{ env.DOMAIN_NAME }}"